#!/usr/bin/env bash

# remove script
# Author: jcolours
# Date: 2026-05-26
# Description: removes tool from system

if [ "$EUID" -ne 0 ]; then 
  echo "Please use sudo..."
  exit 1
fi 

echo "Removing tool..."

rm -rf /usr/local/lib/gapush
rm -f /usr/local/bin/gapush 

echo "Tool has been removed..."

exit 0
